### ISSUE TITLE
pkg_resources.VersionConflict: (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))

### ISSUE THREAD

**Issue by ghost** [m2-farzan/ros2-foxy-PKGBUILD#12]
I just executed `yay -S ros2-foxy`
then a lot of errors that are `colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0')`
```
[13.272s] ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.prefix_path.catkin': (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 120, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 168, in load_entry_point
    return entry_point.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2454, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2477, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))

```

**Comment by m2-farzan** [comment]
Please see m2-farzan/ros2-galactic-PKGBUILD#14

P.S. I strongly recommend galactic over foxy. The nature of Arch makes it difficult to maintain older versions. Even galactic package has 3 open issues, and currently requires minor manual interventions (read the issues for more info).

**Comment by ghost** [comment]
I executed `pip3 install colcon-core==0.7.0`, and then `yay -S ros2-galactic`
**I got the same error** `pkg_resources.VersionConflict: (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))`
Then I check `pip list`:
```sh
colcon-argcomplete         0.3.3
colcon-bash                0.4.2
colcon-cd                  0.1.1
colcon-cmake               0.2.26
colcon-common-extensions   0.2.1
colcon-core                0.7.0
colcon-defaults            0.2.6
colcon-devtools            0.2.3
colcon-library-path        0.2.1
colcon-metadata            0.2.5
colcon-notification        0.2.13
colcon-output              0.2.12
colcon-package-information 0.3.3
colcon-package-selection   0.2.10
colcon-parallel-executor   0.2.4
colcon-pkg-config          0.1.0
colcon-powershell          0.3.7
colcon-python-setup-py     0.2.7
colcon-recursive-crawl     0.2.1
colcon-ros                 0.3.22
colcon-test-result         0.3.8
colcon-zsh                 0.4.0
```
But `colcon-core  0.7.0`

**Comment by m2-farzan** [comment]
Hmm...
Can you try upgrading colcon-core globally i.e. using `sudo pip3 install ...` with `sudo`?

**Comment by ghost** [comment]
`sudo` does work. Also, I found `colcon-core` in `/usr/lib/python3.10/site-packages/` where versions 0.6.1 and 0.7.0 coexist. After I uninstalled it twice and reinstalled 0.7.0, the problem was solved. **Thank you so much for your selfless help, I learned a lot from you.**

**Comment by m2-farzan** [comment]
No problem! I, too, learn from these discussions.
